1. Create a 1D NumPy array of integers from 10 to 20.
2. Reshape a 1D array of integers from 1 to 16 into a 4x4 matrix.
3.  Create a 2D array of shape (4, 5) with integers from 1 to 20 and access the element in the 3rd row and 4th column.
4. Create a 2D array with shape (4, 6) and from the 2nd and 3rd rows, slice elements from index 2 to index 5.
5. Convert a 1D array with 12 elements into a 3D array with shape (2, 3, 2). The outermost dimension will have 2 arrays that contain 3 arrays, each with 2 elements.
6. Create a 1D array of 15 elements and reshape it into a 3x5 matrix. Then, extract the 2nd row as a 1D array.
7. Create a 3D array with shape (2, 4, 3) and from the 1st array, slice elements from the 2nd and 3rd rows.
8. Create a filter array that will return only even elements from the original array.
9. Create a DataFrame with columns 'Product' and 'Price' with the following data: [['Apple', 1.2], ['Banana', 0.8], ['Cherry', 2.5]]. Filter the DataFrame to include only rows where Price is greater than 1.
10. Create a DataFrame with columns 'Name' and 'Age' with the following data: [['Alice', 24], ['Bob', 19], ['Charlie', 22]]. Filter the DataFrame to include only rows where Age is greater less 20.

In [ ]:
#ques1
import numpy as np

arr = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

print(arr)


[10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#ques2
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
newarr = arr.reshape(4, 4)

print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
#ques3
import numpy as np

arr = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])
newarr = arr.reshape(4, 5)
print('element of 3rd row and 4th column: ', newarr[2, 3])

print(newarr)

element of 3rd row and 4th column:  14
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [6]:
#ques4
import numpy as np

arr = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11, 12], [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
newarr = arr.reshape(4, 6)
print(newarr)
print('result:')
print(newarr[1:3, 2:5])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
result:
[[ 9 10 11]
 [15 16 17]]


In [5]:
#ques5
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print('Result:')
print(newarr)

Result:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
#ques6
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
newarr = arr.reshape(3,5)
print('Result:', newarr)
arr_1D = newarr[1]
print('1D array of 2nd row is:', arr_1D)


Result: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
1D array of 2nd row is: [ 6  7  8  9 10]


In [4]:
#ques7
import numpy as np

arr = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
newarr = arr.reshape(2, 4, 3)
print(newarr)
sliced_elements = newarr[0, 1:3, :]
print('result:')
print( sliced_elements)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
result:
[[4 5 6]
 [7 8 9]]


In [2]:
#ques8
import numpy as np

arr = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

newarr = arr.reshape(2, 4, 3)
print("3D Array:")
print(newarr)

filter_array = (newarr % 2 == 0)

even_elements = newarr[filter_array]
print("Even Elements:")
print(even_elements)

3D Array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
Even Elements:
[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [14]:
#ques9
import numpy as np
import pandas as pd

data = [['Apple', 1.2], ['Banana', 0.8], ['Cherry', 2.5]]
df = pd.DataFrame(data, columns=['Product', 'Price'])
print(df)

filtered_df = df[df['Price'] > 1]
print("Filtered Data (Price > 1):")
print(filtered_df)


  Product  Price
0   Apple    1.2
1  Banana    0.8
2  Cherry    2.5
Filtered Data (Price > 1):
  Product  Price
0   Apple    1.2
2  Cherry    2.5


In [13]:
#ques9
import numpy as np
import pandas as pd

data_np = np.array([('Alice', 24), ('Bob', 19), ('Charlie', 22)], dtype=[('Name', 'U10'), ('Age', 'i4')])
print("Original Structured Array:")
print(data_np)

df = pd.DataFrame(data_np)
print("DataFrame:")
print(df)

filtered_df = df[df['Age'] < 20]
print("Filtered DataFrame (Age < 20):")
print(filtered_df)



Original Structured Array:
[('Alice', 24) ('Bob', 19) ('Charlie', 22)]
DataFrame:
      Name  Age
0    Alice   24
1      Bob   19
2  Charlie   22
Filtered DataFrame (Age < 20):
  Name  Age
1  Bob   19
